version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
      - TZ=Europe/Moscow
    expose:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: bot.dockerfile
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./:/bot

  manager:
    build:
      context: .
      dockerfile: manager.dockerfile
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./:/manager


volumes:
  postgres-data:
